# Generated by Django 3.1.5 on 2021-01-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210118_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mode_of_payment',
            field=models.CharField(default='Cash On Delivery', max_length=50),
        ),
    ]
