# Generated by Django 3.1.5 on 2021-01-21 10:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20210119_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='disc_per',
            field=models.PositiveIntegerField(default=None, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
